export const GET_REPOS_LIST_BY_USER_ID = 'GET_REPOS_LIST_BY_USER_ID';
export const GET_REPOS_LIST_BY_USER_ID_SUCCESS = 'GET_REPOS_LIST_BY_USER_ID_SUCCESS';
export const GET_REPOS_LIST_BY_USER_ID_FAILURE = 'GET_REPOS_LIST_BY_USER_ID_FAILURE';

export const CLEAR_REPOS_LIST = 'CLEAR_REPOS_LIST';

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_ITEMS_PER_PAGE = 'SET_ITEMS_PER_PAGE';